[tools]
python = "3.14.0"
kubectl = "1.34.2"
terraform = "1.14.0"
starship = "1.24.1"
zoxide = "0.9.8"
gitui = "0.27.0"
golang = "1.24.0"
task = "3.45.5"
"go:github.com/hay-kot/scaffold" = "0.11.0"
"cargo:yazi-fm" = "25.5.31"
"cargo:yazi-cli" = "25.5.31"
neovim = "0.11.5"
go = "1.25.4"
delta = "0.18.2"
"aqua:junegunn/fzf" = "0.67.0"
"cargo:ast-grep" = "0.40.0"
"cargo:tlrc" = "1.12.0"

[settings]
experimental = true
