[tools]
python = "3.14.2"
kubectl = "1.35.0"
terraform = "1.14.3"
starship = "1.24.1"
zoxide = "0.9.8"
gitui = "0.28.0"
task = "3.46.4"
"go:github.com/hay-kot/scaffold" = "0.11.0"
"cargo:yazi-fm" = "25.5.31"
"cargo:yazi-cli" = "25.5.31"
neovim = "0.11.5"
go = "1.25.5"
delta = "0.18.2"
"aqua:junegunn/fzf" = "0.67.0"
"cargo:ast-grep" = "0.40.3"
"cargo:tlrc" = "1.12.0"
tree-sitter = "0.25.10"

[settings]
experimental = true
